### ISSUE TITLE
DOes not work for InfluxDB 0.9.3 or highter

### ISSUE THREAD

**Issue by Papalloon** [mboeru/statsfeeder#1]
The title say it all, the tool does not work anymore sadly.

**Comment by mboeru** [comment]
Hi Papalloon,

I personally use it still with graphite, and have not tested with influx.
Do you have an error or something? I presume you enabled the graphite backport in influx to make it work.

**Comment by Papalloon** [comment]
I tried to use it with graphitereceiver then influxDB.

The data are sent to influxDB but not wrote. Because of that I guess : https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v093-2015-08-26

**Comment by mboeru** [comment]
I've tested with 1.3.2 and it seems to work. The tests were done on influxdb graphite port directly.
root@c0a731d96f9c:/# influxd version
InfluxDB v1.3.2 (git: 1.3 742b9cb3d74ff1be4aff45d69ee7c9ba66c02565)
